name: Run Tests

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  setup-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - uses: actions/setup-node@v4 
        with:
          node-version: 18
      - run: pip install -r requirements.txt
      - run: npm install
        working-directory: ./frontend
      - run: |
            npm run dev &
            echo $! > process.pid
            echo "Background process started with PID $(cat process.pid)."
        working-directory: ./frontend
            
      # Run test scripts here (Test scripts should ALWAYS throw an error or exit with a value > 0 if they fail)
      - run: echo "testing..."
      - run: python ./frontend/tests/test_nav_menu.py
      - run: echo "Test complete"
